"""initial migration

Revision ID: aceafe4e4856
Revises: 
Create Date: 2026-07-06 22:03:19.581743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aceafe4e4856'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('types_of_balances_type_of_trade_id_fkey2'), 'types_of_balances', type_='foreignkey')
    op.drop_constraint(op.f('types_of_balances_user_balance_id_fkey2'), 'types_of_balances', type_='foreignkey')
    op.drop_constraint(op.f('users_balance_user_id_fkey1'), 'users_balance', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_balance_user_id_fkey1'), 'users_balance', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('types_of_balances_user_balance_id_fkey2'), 'types_of_balances', 'users_balance', ['user_balance_id'], ['id'])
    op.create_foreign_key(op.f('types_of_balances_type_of_trade_id_fkey2'), 'types_of_balances', 'types_of_trade', ['type_of_trade_id'], ['id'])
    # ### end Alembic commands ###
