name: CI Pipeline

on: workflow_dispatch

jobs:

  lint:
    name: Lint Code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install requirements
        run:  |
          pip install --upgrade pip
          pip install -r src/backend/services/auth-service/requirements.txt

      - name: Check code style and typing (Mypy, Ruff)
        run: |
          mypy ./src/backend/services/auth-service/src/
          ruff check --fix ./src/backend/services/auth-service/src/ && ruff format ./src/backend/services/auth-service/src/

  test:
    name: Run Tests

    needs: [lint]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/backend/services/auth-service/requirements.txt

      - name: Run tests
        env:
          DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@localhost:5432/test_db
          REDIS_DATABASE_URL: redis://localhost:6379
        run: pytest src/backend/services/auth-service/src/tests/
#  # ===== BUILD DOCKER =====
#  build:
#    name: 🐳 Build Docker Image
#    runs-on: ubuntu-latest
#    needs: [lint, test]  # Запускается только если линтеры и тесты прошли
#
#    steps:
#      - name: 📥 Checkout code
#        uses: actions/checkout@v4
#
#      - name: ️ Build Docker image
#        run: |
#          docker build -t auth-service:${{ github.sha }} ./auth-service
#
#      - name: 🧪 Test Docker image
#        run: |
#          docker run --rm auth-service:${{ github.sha }} python -m pytest tests/ -v
#
#      - name: 🏷️ Tag image for GitHub Registry
#        run: |
#          docker tag auth-service:${{ github.sha }} ghcr.io/${{ github.repository }}/auth-service:${{ github.sha }}
#          docker tag auth-service:${{ github.sha }} ghcr.io/${{ github.repository }}/auth-service:latest
#
#  # ===== SECURITY SCAN =====
#  security:
#    name: 🔒 Security Scan
#    runs-on: ubuntu-latest
#    needs: [build]
#
#    steps:
#      - name: 📥 Checkout code
#        uses: actions/checkout@v4
#
#      - name: 🔍 Scan with Trivy
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: ghcr.io/${{ github.repository }}/auth-service:${{ github.sha }}
#          format: "sarif"
#          output: "trivy-results.sarif"
#          severity: "CRITICAL,HIGH"
#
#      - name: 📤 Upload to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: "trivy-results.sarif"



